---
name: Run tests

on:
  pull_request:

jobs:
  # Use a matrix for AlmaLinux versions
  test:
    strategy:
      matrix:
        almalinux-version: [9]
    name: Run tests on AlmaLinux ${{ matrix.almalinux-version }}
    runs-on: ubuntu-latest
    container: almalinux:${{ matrix.almalinux-version }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          yum install -y python3
          cd tests/
          ./run-tests.sh
